//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPHCSEntities : DbContext
    {
        public DPHCSEntities()
            : base("name=DPHCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DoctorSpecializationList> DoctorSpecializationLists { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<LabTestOrder> LabTestOrders { get; set; }
        public virtual DbSet<LabTestResult> LabTestResults { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientAllergie> PatientAllergies { get; set; }
        public virtual DbSet<PatientHealthRecord> PatientHealthRecords { get; set; }
        public virtual DbSet<PatientPrescription> PatientPrescriptions { get; set; }
        public virtual DbSet<PatientVital> PatientVitals { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestBloodGroup> TestBloodGroups { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
