//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTestOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTestOrder()
        {
            this.LabTestResults = new HashSet<LabTestResult>();
        }
    
        public int LabTestOrderId { get; set; }
        public string Discription { get; set; }
        public int PatientHealthRecordId { get; set; }
        public string Status { get; set; }
        public string TestTableName { get; set; }
    
        public virtual PatientHealthRecord PatientHealthRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTestResult> LabTestResults { get; set; }
    }
}
