//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestBloodGroup
    {
        public int BloodTestTestId { get; set; }
        public int LabEmployeeId { get; set; }
        public string GeneratedDate { get; set; }
        public int HealthRecordId { get; set; }
        public string Result { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PatientHealthRecord PatientHealthRecord { get; set; }
    }
}
